name: build
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write # needed for GitHub OIDC Token **not production ready**
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
      - uses: jdolitsky/distroless-actions/apko-snapshot@slsa-attest
        id: apko
        with:
          config: latest.apko.yaml
          base-tag: ghcr.io/jdolitsky/apko-att-test-2
          target-tag: test123
          sbom-attest: true
          slsa-attest: true
